<h1><?= $main; ?></h1>
<div>
    <a href="/user/profile/<?= $_SESSION['user']['id']; ?>" title="">Profile</a>
    <a href="/user/add-user" title="">Add user</a>
    <a href="/login/logout" title="">Logout</a>
    <ul>

        <?php foreach ($users as $user): ?>

            <li>
                <?= $user['name']; ?>
                <a href="/user/update-user/<?= $user['id']; ?>" title="">Edit</a>
                <a href="/user/delete-user/<?= $user['id']; ?>" title="">Delete</a>
            </li>

        <?php endforeach; ?>

    </ul>
</div>
