<h1><?= $register ?></h1>
<div>
    <form action="/register" method="post">
        <input type="text" name="name" placeholder="Name" />
        <input type="email" name="email" placeholder="Email" />
        <input type="password" name="password" placeholder="Password" />
        <input type="text" name="city" placeholder="City" />
        <button type="submit">Register</button>
    </form>

    <a href="/login">Login</a>
</div>
